import { dom, library } from '@fortawesome/fontawesome-svg-core'

import {
  faArrowLeft as fasArrowLeft,
  faArrowsUpDown as fasArrowsUpDown,
  faBox as fasBox,
  faCheck as fasCheck,
  faChevronDown as fasChevronDown,
  faChevronUp as fasChevronUp,
  faCloudArrowUp as fasCloudArrowUp,
  faDownload as fasDownload,
  faDroplet as fasDroplet,
  faExclamationTriangle as fasExclamationTriangle,
  faEye as fasEye,
  faFileCsv as fasFileCsv,
  faFileImport as fasFileImport,
  faGear as fasGear,
  faGlobe as fasGlobe,
  faGripVertical as fasGripVertical,
  faHouse as fasHouse,
  faInfoCircle as fasInfoCircle,
  faLightbulb as fasLightbulb,
  faList as fasList,
  faPenToSquare as fasPenToSquare,
  faPhone as fasPhone,
  faPlus as fasPlus,
  faSave as fasSave,
  faShippingFast as fasShippingFast,
  faSort as fasSort,
  faSpinner as fasSpinner,
  faTable as fasTable,
  faTimes as fasTimes,
  faTrash as fasTrash,
  faTruck as fasTruck,
  faUsers as fasUsers,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  fasArrowLeft,
  fasArrowsUpDown,
  fasBox,
  fasCheck,
  fasChevronDown,
  fasChevronUp,
  fasCloudArrowUp,
  fasDownload,
  fasDroplet,
  fasExclamationTriangle,
  fasEye,
  fasFileCsv,
  fasFileImport,
  fasGear,
  fasGlobe,
  fasGripVertical,
  fasHouse,
  fasInfoCircle,
  fasLightbulb,
  fasList,
  fasPenToSquare,
  fasPhone,
  fasPlus,
  fasSave,
  fasShippingFast,
  fasSort,
  fasSpinner,
  fasTable,
  fasTimes,
  fasTrash,
  fasTruck,
  fasUsers
)

dom.watch()
